openapi: 3.0.0
info:
  title: Sweet Delights API
  version: 3.0.0
  description: Полный API для интернет-магазина сладостей

servers:
  - url: https://d5dimdj7itkijbl4s0g4.y5sm01em.apigw.yandexcloud.net

paths:
  # ========== PRODUCTS ==========
  /products:
    get:
      summary: Получить все товары
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e4idepedeld78laqoc
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Список товаров
          content:
            application/json:
              schema:
                type: array
    post:
      summary: Создать товар
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7ckel7qhqbpfe4bed
        service_account_id: aje47rf2630q59equess
      responses:
        '201':
          description: Товар создан
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  /products/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Получить товар по ID
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e456gq1squ9ai8diod
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Товар
    put:
      summary: Обновить товар
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e5oksvmessk4oqvpcf
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Товар обновлен
    delete:
      summary: Удалить товар
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4esrv1g01lkk42oui5s
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Товар удален
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  # ========== CATEGORIES ==========
  /categories:
    get:
      summary: Получить все категории
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e2ld9g5nijdfj1533f
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Список категорий
    post:
      summary: Создать категорию
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ell676278ilsv3p613
        service_account_id: aje47rf2630q59equess
      responses:
        '201':
          description: Категория создана
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  /categories/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    put:
      summary: Обновить категорию
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e9k30qmtekul9dkinj
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Категория обновлена
    delete:
      summary: Удалить категорию
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e3f9uaj7cpro1dbi6r
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Категория удалена
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, PUT, DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  # ========== REVIEWS ==========
  /reviews:
    get:
      summary: Получить отзывы
      parameters:
        - name: productId
          in: query
          required: false
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ebvaaosp0rgq42lgtt
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Список отзывов
    post:
      summary: Создать отзыв
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e5rtbinbsuejlvpccr
        service_account_id: aje47rf2630q59equess
      responses:
        '201':
          description: Отзыв создан
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  /reviews/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    delete:
      summary: Удалить отзыв
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4evki4lg1pk0lvtpefv
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Отзыв удален
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  # ========== PROMO CODES ==========
  /promocodes:
    get:
      summary: Получить все промокоды
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ecp2o90p3muttclklo
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Список промокодов
    post:
      summary: Создать промокод
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7rih2fc2crfnuk4gs
        service_account_id: aje47rf2630q59equess
      responses:
        '201':
          description: Промокод создан
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  /promocodes/validate:
    post:
      summary: Валидировать промокод
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e40g65ao5k8qm4s1t0
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Результат валидации
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'POST, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  /promocodes/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    put:
      summary: Обновить промокод
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eid0ja8kcvi9pgquhj
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Промокод обновлен
    delete:
      summary: Удалить промокод
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e0npv20cddnaeub43d
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Промокод удален
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'PUT, DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  # ========== CART ==========
  /cart/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Получить корзину
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4esojcuk9b5n3t778dj
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Корзина
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  /cart:
    post:
      summary: Сохранить корзину
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ehmac1vf3aaurmkd4v
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Корзина сохранена
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'POST, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  # ========== WISHLIST ==========
  /wishlist/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Получить избранное
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eejdpj1c0dkf7lol5f
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Избранное пользователя
    put:
      summary: Обновить избранное
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e3lqn3hen9e35nu1vk
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Избранное обновлено
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, PUT, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  # ========== ORDERS ==========
  /orders:
    post:
      summary: Создать заказ
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4endddm1udm56n8ilqm
        service_account_id: aje47rf2630q59equess
      responses:
        '201':
          description: Заказ создан
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'POST, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  /orders/all:
    get:
      summary: Получить все заказы (админ)
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ealrgnc0j0dbckf0al
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Все заказы
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  /orders/user/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Получить заказы пользователя
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e3i8vbihb62gg0lece
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Заказы пользователя
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  /orders/{id}/status:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    put:
      summary: Обновить статус заказа
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4en5d1n2qjq9ha2qtse
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Статус обновлен
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'PUT, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  /orders/{id}/hide:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    put:
      summary: Скрыть заказ
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e3blt2bq3njqj9p98u
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Заказ скрыт
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'PUT, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK

  /orders/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    delete:
      summary: Удалить заказ
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ej0takv92d3e144oqj
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Заказ удален
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
        content:
          application/json: '{}'
      responses:
        '200':
          description: OK
