openapi: 3.0.0
info:
  title: Sweet Delights API
  version: 1.0.0
  description: API для интернет-магазина сладостей

paths:
  /products:
    get:
      summary: Получить все товары
      operationId: getAllProducts
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e4idepedeld78laqoc
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Список товаров
          content:
            application/json:
              schema:
                type: array
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'

  /products/{id}:
    get:
      summary: Получить товар по ID
      operationId: getProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e456gq1squ9ai8diod
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Товар
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'

  /categories:
    get:
      summary: Получить все категории
      operationId: getAllCategories
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4c21d9e5e1jd31537f
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Список категорий
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'

  /cart/{userId}:
    get:
      summary: Получить корзину пользователя
      operationId: getCart
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4esojcuk9b5n3t778dj
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Корзина
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'

  /cart:
    post:
      summary: Сохранить корзину
      operationId: saveCart
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ehmac1vf3aaurmkd4v
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Корзина сохранена
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'

  /orders:
    post:
      summary: Создать заказ
      operationId: createOrder
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4endddm1udm56n8ilqm
        service_account_id: aje47rf2630q59equess
      responses:
        '200':
          description: Заказ создан
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Access-Control-Allow-Origin': '*'
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
          'Access-Control-Allow-Headers': 'Content-Type, Authorization'
